table Fact
	isHidden
	lineageTag: c4a5391e-c39b-4a5a-90ee-97b35dc338bf

	measure 'Total Revenue' = SUM([Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 81f29674-328c-4ea6-ad4d-25ff6404e00c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Material Costs' = SUM([Material Costs])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e3ac0df2-116c-45fc-9d9e-5375e248f2aa

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Labor Costs Variable' = SUM([Labor Costs Variable])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b800e123-f72c-4791-83fb-34327e9c57e8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Taxes' = SUM([Taxes])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 25e707b1-1be5-47f9-92ab-1b7282fef963

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Rev for Exp Travel' = SUM([Rev for Exp Travel])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a82f9d2d-645b-41a4-aff1-9e4a4c287730

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Travel Expenses' = SUM([Travel Expenses])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d410f6cc-7404-4dcf-9ef5-d7c3d128aea0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Cost Third Party' = SUM([Cost Third Party])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8d335a72-71e5-49b2-8ee1-f8a96db9423f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Subscription Revenue' = SUM([Subscription Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0c0f0112-c90e-44c2-876c-304a9d8f084b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin' = [Total Revenue]-[Total COGS]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 822210da-3195-4e2f-adab-fafb123999af

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure GM% = DIVIDE([Gross Margin],[Total Revenue])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8983c7d1-789a-4b9b-b9ed-7fcafa758d5c

	measure 'YTD Revenue' = TOTALYTD(SUM([Revenue]),'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b292cc15-6f72-4aff-ab4d-da43ee11ecdd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total COGS' = [Sum of Material Costs]+[Sum of Labor Costs Variable]+[Sum of Taxes]+[Sum of Rev for Exp Travel]+[Sum of Travel Expenses]+[Sum of Cost Third Party]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: dab8de6c-207d-4a5c-b6c5-42d7f5db1b16

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD COGS' = TOTALYTD([Total COGS],'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ceadff1a-f3c6-4cd6-8b41-19979ffa932c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD Gross Margin' = TOTALYTD([Gross Margin],'Date'[Date])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3bcae23c-db24-49b9-92da-b1787f0120b8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue SPLY' = CALCULATE([Total Revenue],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c5a62619-5428-4d3c-b79d-d0304deb15e9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Margin SPLY' = CALCULATE([Gross Margin],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 551495b3-7230-4856-9add-1d66564249c8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'GM% SPLY' = [Gross Margin SPLY]/[Revenue SPLY]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 85d9dcea-6132-4f5f-bc52-a11ad517bf6c

	measure 'YTD GM%' = [YTD Gross Margin]/[YTD Revenue]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 50d09c42-f691-4f85-aee3-cb584a8c4a20

	measure 'YTD Revenue SPLY' = CALCULATE([YTD Revenue],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a20f6d90-dd6e-44ef-aceb-77daa0a3ea73

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'COGS SPLY' = CALCULATE([Total COGS],SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8f4c190c-9675-4198-98a7-5efba247b0a2

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD COGS SPLY' = CALCULATE([YTD COGS],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 11b46b47-606f-48e5-b0f5-a0eeb91c30d0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD GM% SPLY' = [YTD GM SPLY]/[YTD Revenue SPLY]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a61991c6-4d32-4334-8941-a7b84a713985

	measure 'YTD GM SPLY' = CALCULATE([YTD Gross Margin],SAMEPERIODLASTYEAR(DATESYTD('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b4710a0a-51c5-4c69-b4cd-baeabcc877cc

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY Rev Var' = [Total Revenue]-[Revenue SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: afde093a-0bb7-46d3-897f-ae8d25cfb68c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY GM Var' = [Gross Margin]-[Gross Margin SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 26b2ba2e-9ebb-4897-93ab-78727b789b47

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY Rev Growth' = IF([Revenue SPLY],[YoY Rev Var]/[Revenue SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ca72728e-7c46-4bb9-b0b8-63794c68685e

	measure 'YoY GM Growth' = IF([Gross Margin SPLY],[YoY GM Var]/[Gross Margin SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 70359a2e-a7dc-4b47-98c6-6d386ae7aaea

	measure 'YoY YTD Rev Var' = [YTD Revenue]-[YTD Revenue SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 41deacae-aea5-4304-8498-891dcaa760fd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY COGS Var' = [Total COGS]-[COGS SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ebcd0400-a397-43b4-a61e-8940a5d9bdf1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY YTD COGS Var' = [YTD COGS]-[YTD COGS SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 07d95a71-e69b-4c4e-b10c-d76f52dcd456

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY YTD GM% Var' = [YTD GM%]-[YTD GM% SPLY]
		formatString: #,0
		lineageTag: 5368f215-6772-4c8b-b0a8-c3ff24ca92b5

	measure 'YoY YTD GM Var' = [YTD Gross Margin]-[YTD GM SPLY]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2f693ada-bd5d-4674-9804-bd6396095c4f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YoY GM %Var' = [GM%]-[GM% SPLY]
		lineageTag: 783a14cd-10b0-443c-bec1-5e2258649db3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY YTD Rev Growth' = IF([YTD Revenue SPLY],[YoY YTD Rev Var]/[YTD Revenue SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4ee1b118-8051-4a8d-bc9c-d0ef064c9292

	measure 'YoY COGS Growth' = IF([COGS SPLY],[YoY COGS Var]/[COGS SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8a3490d1-7980-4561-a812-d1634f2cbdc6

	measure 'YoY YTD COGS Growth' = IF([YTD COGS SPLY],[YoY YTD COGS Var]/[YTD COGS SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ec695b84-16f4-4e3b-a756-f65321cb8161

	measure 'YoY YTD GM Growth' = IF([YTD GM SPLY],[YoY YTD GM Var]/[YTD GM SPLY],BLANK())
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8f738f96-3059-4e80-a2f7-eec8dcb919aa

	measure '# of Customers' = DISTINCTCOUNT([Customer Key])
		lineageTag: 1f44ff34-c6b2-4369-ad75-b138c11c0789

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# of Products' = DISTINCTCOUNT([Product Key])
		lineageTag: 79565e70-96e4-4409-a1b8-61a724fbf86b

		annotation PBI_FormatHint = {"isText":true}

	measure 'Revenue Budget' = CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]="Budget"))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c32c67a8-5183-4bf1-a974-5fe49cea85c1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Var to Budget' = [RevenueTY]-[Revenue Budget]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d8a53012-280d-4d61-b4a7-27906d104d3c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Var % to Budget' = DIVIDE([Revenue Var to Budget], [RevenueTY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: faf6118c-1c2c-4b59-b509-c3558fdccafc

	measure RevenueTY = CALCULATE([Total Revenue], FILTER(Scenario, Scenario[Scenario]="Actual"))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e0b28002-e91e-4b59-b40b-8ad4a928e349

		kpi
			targetExpression = 'Fact'[Revenue Budget]
			targetFormatString: \$#,0;(\$#,0);\$#,0
			statusGraphic: Traffic Light - Single
			statusExpression = ```
				var x='Fact'[RevenueTY]/'Fact'[_RevenueTY Goal] return
				if(ISBLANK(x),BLANK(),
				        If(x<0.95,-1,
					    If(x<1,0,1)
				    )
				)
				
				```

			annotation GoalType = Measure

			annotation KpiStatusType = Linear

			annotation KpiThresholdType = Percentage

			annotation KpiThresholdOrdering = Ascending

			annotation KpiThresholdCount = 2

			annotation KpiThreshold_0 = 95

			annotation KpiThreshold_1 = 100

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sum of Revenue' = SUM('Fact'[Revenue])
		lineageTag: ae3ec9ec-80c0-40d3-90d8-cff3e30b2de6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer Key'
		dataType: int64
		isHidden
		lineageTag: b898372e-688c-41ac-832b-45fd23bd96b5
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Key'
		dataType: string
		isHidden
		lineageTag: 8ea4944f-3596-4d55-b557-47be677bdddc
		summarizeBy: none
		sourceColumn: Product Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'BU Key'
		dataType: double
		isHidden
		lineageTag: aee09548-6b4b-42de-94d7-393bb715f04e
		summarizeBy: none
		sourceColumn: BU Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Scenario Key'
		dataType: int64
		isHidden
		lineageTag: 43174e26-eeaa-4643-9f4e-348c54f77739
		summarizeBy: none
		sourceColumn: Scenario Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Revenue
		dataType: double
		isHidden
		lineageTag: bc8e59d0-bc08-4542-9c25-478cc8971fff
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Material Costs'
		dataType: double
		isHidden
		lineageTag: cd6ecd56-8c8a-404f-8ca3-b3df270a6ede
		summarizeBy: sum
		sourceColumn: Material Costs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Labor Costs Variable'
		dataType: double
		isHidden
		lineageTag: bdd024c6-8da7-4033-9b9b-e24711e9e8c4
		summarizeBy: sum
		sourceColumn: Labor Costs Variable

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Taxes
		dataType: double
		isHidden
		lineageTag: 3edbb23b-8d87-465c-ab77-e0a32e38532d
		summarizeBy: sum
		sourceColumn: Taxes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rev for Exp Travel'
		dataType: double
		isHidden
		lineageTag: c72c0fa1-b6a3-4e1e-9fd3-b506f890fd43
		summarizeBy: sum
		sourceColumn: Rev for Exp Travel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Travel Expenses'
		dataType: double
		isHidden
		lineageTag: 9aa29e0c-ddea-4b03-9b25-1b0a4135e30a
		summarizeBy: sum
		sourceColumn: Travel Expenses

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Third Party'
		dataType: double
		isHidden
		lineageTag: 4ff88f5b-8f2f-466e-af1a-3cbd8ff15949
		summarizeBy: sum
		sourceColumn: Cost Third Party

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subscription Revenue'
		dataType: double
		isHidden
		lineageTag: a79908cf-25da-4d26-80b0-ee902ebdde84
		summarizeBy: sum
		sourceColumn: Subscription Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearPeriod
		dataType: string
		isHidden
		lineageTag: 111654ce-024a-4b50-b29d-d72c26d72509
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation SummarizationSetBy = Automatic

	partition Fact = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 YearPeriod#(lf)      ,[KNDNR] [Customer Key]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,1 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.20 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f, mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 210 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'#(lf)union all #(lf)SELECT #(lf)       concat([GJAHR] , substring([PERDE], 2, 2) ) + 400 PeriodYear#(lf)      ,[KNDNR] [Customer]#(lf)      --,[ARTNR] [Product]#(lf)      --,[FKART] [Billing Type]#(lf)      --,[FRWAE] [Currency Key]#(lf)      --,[VTWEG] [Distribution Channel]#(lf)   ,[VTWEG] [Product Key]#(lf)      --,[PRCTR] [Profit Center]#(lf)   ,pc.[Profit Center Key] [BU Key]#(lf)   ,2 [Scenario Key]#(lf)      --,[KMMAKL] [Material Group]#(lf)      ,[ERLOS]*1.4 [Revenue]#(lf)      ,[VVMAT] [Material Costs]#(lf)      ,[VVLCV] [Labor Costs Variable]#(lf)      ,[VVN30] [Taxes]#(lf)      ,[VV910] [Rev for Exp Travel]#(lf)      ,[VV950] [Travel Expenses]#(lf)      ,[VV970] [Cost Third Party]#(lf)      ,[VVYSV] [Subscription Revenue]#(lf)  FROM OSQ.[osq].[CE11010] f tablesample (85 percent),  mds.mdm.profitcenter pc#(lf)where  [MANDT]  = 300 and concat([GJAHR] , substring([PERDE], 2, 2) ) < 201012 and f.PRCTR = pc.PCName and [FRWAE] = 'USD'"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Customer Key", "Customer Key"}, {"Product Key", "Product Key"}, {"BU Key", "BU Key"}, {"Scenario Key", "Scenario Key"}, {"Revenue", "Revenue"}, {"Material Costs", "Material Costs"}, {"Labor Costs Variable", "Labor Costs Variable"}, {"Taxes", "Taxes"}, {"Rev for Exp Travel", "Rev for Exp Travel"}, {"Travel Expenses", "Travel Expenses"}, {"Cost Third Party", "Cost Third Party"}, {"Subscription Revenue", "Subscription Revenue"}, {"YearPeriod", "YearPeriod"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer Key", Int64.Type}, {"Product Key", type text}, {"BU Key", type number}, {"Scenario Key", Int64.Type}, {"Revenue", type number}, {"Material Costs", type number}, {"Labor Costs Variable", type number}, {"Taxes", type number}, {"Rev for Exp Travel", type number}, {"Travel Expenses", type number}, {"Cost Third Party", type number}, {"Subscription Revenue", type number}, {"YearPeriod", type text}})
				in
				    #"Changed Type"

