table Industry
	lineageTag: 66ab11bc-0bbc-46d0-8da5-afce22090dea

	column ID
		dataType: int64
		isHidden
		isKey
		keepUniqueRows
		lineageTag: 9fd6fc7b-1220-4aec-a362-361b9a3de8a2
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Industry
		dataType: string
		keepUniqueRows
		lineageTag: 4d3c0dda-e2b4-4332-921f-8298608ed985
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Image
		dataType: binary
		lineageTag: 3c5e32cc-7e82-46d7-ad79-dc02b0a2d825
		dataCategory: Image
		isDefaultImage
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Industry = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [dbo].[Industry].*   FROM [dbo].[Industry]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ID", "ID"}, {"Industry", "Industry"}, {"Image", "Image"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ID", Int64.Type}, {"Industry", type text}, {"Image", type binary}})
				in
				    #"Changed Type"

