table Scenario
	lineageTag: a9e55046-693e-4fa7-a466-2704d8d794d7

	column 'Scenario Key'
		dataType: int64
		isHidden
		lineageTag: 19acc04a-adcc-4309-8165-f2f7e3b8ea31
		summarizeBy: none
		sourceColumn: Scenario Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scenario
		dataType: string
		lineageTag: 907a8794-e436-47ca-b820-2cca6a4484ae
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Scenario = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXJMLilNzFGK1YlWMgJynUpT0lNLlGJjAQ==", BinaryEncoding.Base64), Compression.Deflate))),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Column1", "Scenario Key"}, {"Column2", "Scenario"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Scenario Key", Int64.Type}, {"Scenario", type text}})
				 in
				    #"Changed Type"

