table Product
	lineageTag: 41173543-42e6-4bf9-96a4-379c824a1385

	column 'Product Key'
		dataType: int64
		isHidden
		lineageTag: f850de18-11fd-4337-9b20-918e3d3148e3
		summarizeBy: none
		sourceColumn: Product Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product
		dataType: string
		lineageTag: 900ee7d3-0d78-4c96-a2d4-ad79003cfdce
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Product = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lEKzi9LVIrViVYyAvECijJzS4vBfGMQ3yW/KD8dIm8C4rvnJKZkQhVYgAR8PXXNjSBcI5B8aV5eapFSbCwA", BinaryEncoding.Base64), Compression.Deflate))),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Column1", "Product Key"}, {"Column2", "Product"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Product Key", Int64.Type}, {"Product", type text}})
				 in
				    #"Changed Type"

