table Date
	lineageTag: 33b2e06d-1253-420d-9410-00dada17fe49
	dataCategory: Time

	column YearPeriod
		dataType: string
		lineageTag: 9ff43bf2-22bf-45e8-bbdf-1a5efa8d862c
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year
		dataType: int64
		lineageTag: bf1f5986-0854-4b9e-b9f1-f16641fbe2cc
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period
		dataType: string
		lineageTag: 2bc87769-42b9-4869-bba4-6d0521b7a9a3
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 3dff52d6-feb9-43a1-8836-0e9e9cf77d6e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: db9c55a6-9978-4ac0-88b4-4f07ed8945a3
			defaultHierarchy: LocalDateTable_39c22ddb-27f3-4e6c-8a44-a3380850fcb4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: f3165709-ba85-4486-aca1-68fc4f5444fb
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column QtrID
		dataType: string
		lineageTag: a1b1e163-4a70-4a66-a803-acb6a5bfe4e6
		summarizeBy: none
		sourceColumn: QtrID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Qtr
		dataType: string
		lineageTag: 5dab1193-a308-4211-a59e-ede1237b26a0
		summarizeBy: none
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	hierarchy YQM
		lineageTag: cfd9130b-03d9-4d8c-a0bb-b3b41a649b66

		level Year
			lineageTag: 71b71c64-ac19-4040-94b8-449e5c359fa3
			column: Year

		level Qtr
			lineageTag: 0c88c7bc-fe44-48c8-9f30-501453d16ed3
			column: Qtr

		level Month
			lineageTag: 6961d029-bc68-4574-bcef-5fe389b1f378
			column: Month

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT#(lf)       concat([Year], [period]) YearPeriod#(lf)#(tab)  ,[Year]#(lf)      ,[Period]#(lf)      ,[Date]#(lf)      ,[Month]#(lf)      ,[QtrID]#(lf)      ,[Qtr]#(lf)  FROM [MDS].[mdm].[fiscalperiod]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"YearPeriod", "YearPeriod"}, {"Year", "Year"}, {"Period", "Period"}, {"Date", "Date"}, {"Month", "Month"}, {"QtrID", "QtrID"}, {"Qtr", "Qtr"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"YearPeriod", type text}, {"Year", Int64.Type}, {"Period", type text}, {"Date", type datetime}, {"Month", type text}, {"QtrID", type text}, {"Qtr", type text}})
				in
				    #"Changed Type"

	annotation __PBI_LegacyCustomDateTable = true

