table Executive
	lineageTag: 99382395-0f2a-451e-b4d3-f1f32146ffbf

	column ID
		dataType: int64
		isHidden
		isKey
		keepUniqueRows
		lineageTag: 54be392e-02e8-4353-b3a5-784e10bad1f4
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Name
		dataType: string
		lineageTag: fb66b914-2364-4329-84cf-0d666d355afe
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Img
		dataType: binary
		lineageTag: 624d08e4-534b-4f44-bdfe-10f9d2fdbbfd
		dataCategory: Image
		isDefaultImage
		summarizeBy: none
		sourceColumn: Img

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Executive = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [dbo].[Executive].*   FROM [dbo].[Executive]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ID", "ID"}, {"Name", "Name"}, {"Img", "Img"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ID", Int64.Type}, {"Name", type text}, {"Img", type binary}})
				in
				    #"Changed Type"

