table State
	lineageTag: eda132e0-75a8-4e5e-a921-8b2f04a8d14e

	column StateCode
		dataType: string
		lineageTag: 2f38d46c-0c71-4cde-a0d2-955aef57608c
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: StateCode

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column State
		dataType: string
		lineageTag: 4c108fbd-ceff-4705-87ca-eacf8d22281e
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Region
		dataType: string
		lineageTag: b6057dad-1d5b-47ab-b6d8-58c16ff2f1b0
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition State = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="select StateShort StateCode, StateName State, Region from MDS.mdm.state"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"StateCode", "StateCode"}, {"State", "State"}, {"Region", "Region"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"StateCode", type text}, {"State", type text}, {"Region", type text}})
				in
				    #"Changed Type"

